name: Manual Trigger Workflow with username
#get username information
on: 
  workflow_dispatch: null

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the username
        run: echo The username is ${{ inputs.username }}
