name: Manual Trigger Workflow for raffle
on: 
  workflow_dispatch: null

jobs:
  publish-winners:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Send the message
        run: bun install && bun run src/index.ts
