name: Manual Trigger Workflow for raffle
on: 
  workflow_dispatch: null

jobs:
  publish-winners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: create env file
        run: |
          touch .env
          echo SIGNER_UUID=${{ secrets.SIGNER_UUID }} >> .env
          echo NEYNAR_API_KEY=${{ secrets.NEYNAR_API_KEY }} >> .env
      - run: bun install
      - run: bun run src/index.ts
